{% set name = "snowflake.core" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/snowflake_core-{{ version }}.tar.gz
  sha256: 8f93a72fb59799949a3337b6ab529a9169fec10037cefd7ac538b500211d9c0c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - atpublic >=4
    - pydantic >=2
    - python-dateutil >=2.8.2
    - requests
    - snowflake-connector-python
    - pyyaml
    - urllib3

test:
  imports:
    - snowflake.core
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Snowflake Python API for Resource Management
  home: https://www.snowflake.com/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sfc-gh-dyadav
    - sfc-gh-ema
    - sfc-gh-mkeller
