{% set name = "snowflake.core" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/snowflake_core-{{ version }}.tar.gz
  sha256: 242d9635aea06dc2a5e5494ceb6077c76da93bd102ef6e5b477d6820c7d209d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - certifi
    - pydantic >=2
    - python-dateutil >=2.8.2
    - requests
    - snowflake-connector-python
    - pyyaml
    - urllib3

test:
  imports:
    - snowflake.core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Snowflake Python API for Resource Management
  home: https://www.snowflake.com/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sfc-gh-kolszewski
    - sfc-gh-kwasilewski
